### ISSUE TITLE
How cache control and response conditional with 304

### ISSUE THREAD

**Issue by kkazuo** [jannik4/tower-serve-static#5]
Hi, Thank you for making great crate.

How can I add etag cache-control header and conditional response with 304 if etag match?
It's important for browser side caching.

Thanks

**Comment by jannik4** [comment]
Hello!

it's been a long time since I used this myself. But I think the easiest way will be to write a custom [service](https://docs.rs/tower-service/0.3.2/tower_service/trait.Service.html) that wraps the `ServeDir`/`ServeFile` service. These services essentially just map a request to a response. So you should be able to hook into this.

I hope this helps.

**Comment by kkazuo** [comment]
@jannik4 Thanks for the advice!  I'll give it a try.

**Comment by kkazuo** [comment]
@jannik4 I am trying to supports conditional response with as “metadata" feature flag.
Could you consider the PR #6 ?

**Comment by kkazuo** [comment]
#6 has merged!
@jannik4 Thank you.
